name: CI

on:
  push:
    paths:
      - "Assets/**"
      - ".github/**"
  pull_request:
    paths:
      - "Assets/**"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Build
        run: |
          mkdir build
          find ./Assets/Plugins/ -name \*.meta > metaList

      - name: create-unitypackage
        uses: pCYSl5EDgo/create-unitypackage@v1
        with:
          package-path: build/unity-interface-support.unitypackage
          include-files: metaList

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: unitypackage
          path: build/unity-interface-support.unitypackage
